apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyclaim-backend
  labels:
    name: easyclaim-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: easyclaim-backend
  template:
    metadata:
      name: easyclaim-backend
      labels:
        name: easyclaim-backend
    spec:
      containers:
        - name:  easyclaim-backend
          image: vigneshsweekaran/easyclaim-backend:latest-arm64
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: "/config"
      volumes:
      - name: config-volume
        configMap:
          name: easyclaim-backend
          items:
          - key: application
            path: application.properties
